### ISSUE TITLE
post add separators&scissors on saved PDF without separators

### ISSUE THREAD

**Issue by elvisbegovic** [manuelbl/SwissQRBill#13]
# 🚀 Feature request

### Description
iso20022 specs: 
If printable qrinvoice: PDF need to be without separator
If electronic/mailed qrinvoice: PDF need to be with separatortype border+scissors

As a web app developer when an app generate a qrinvoice we always want it to be printable PDF  (without separator) and we **archive/save** this PDF and **never** regenerate it.
But if later a destinator ask for a copy/reminder maybe we aim to sent it by email and we want separators&scissors on this saved pdf.
We achieved this by sugest two options on download button
1. download original pdf (so without separators)
2. download original pdf + edit this pdf to add border&scissors 

### Solution I'd like
Have a clean way with this lib to post-add separator canvas only on a pdf page, same option we currently have to generate complete qrinvoice, idea:
```
try (PDFCanvas canvas = new PDFCanvas(invoiceQRBillWithoutScissors, PDFCanvas.LAST_PAGE)) {
            QRBill.drawSeparators(SeparatorType.DOTTED_LINE_WITH_SCISSORS, canvas);
            Path path = Paths.get("invoice-1.pdf");
            canvas.saveAs(path);
            System.out.println("Invoice 1 saved at " + path.toAbsolutePath());
        }
```

What you think ?

**Comment by manuelbl** [comment]
I understand the use case and will have a look at it. Thanks for the proposal.

**Comment by elvisbegovic** [comment]
What reactivity !! 👍 
Is PR welcome ? I'd rather you did it, it's straightforward to do with your simple/nice api by expose one methods.

at first flance to your code this should be enough
```
// BillLayout.java
BillLayout(Canvas graphics) {
      this.graphics = graphics;
}

public void drawBorder(SeparatorType st, OutputSize os) throws IOException {...}

// QRBill.java
public static any? drawSeparator(Canvas c, SeparatorType st, OutputSize os) {
    BillLayout layout = new BillLayout(c);
    layout.drawBorder(st, os);
}
```

Might be even easier

**Comment by manuelbl** [comment]
A PR is welcome but I can easily do it myself. I'll put some thought into the API later today.

**Comment by manuelbl** [comment]
Version 2.3.2 contains a new method QRBill.drawSeparators(), very similar to what you have proposed.

**Comment by elvisbegovic** [comment]
thank you, waiting for it on https://mvnrepository.com/artifact/net.codecrete.qrbill/qrbill-generator/2.3.2 to update deps & get a try
