### ISSUE TITLE
Decoding

### ISSUE THREAD

**Issue by endovitskayaV** [manuelbl/SwissQRBill#14]
Could you please tell me whether there is a way to decode swiss qr (as image)?
I found only encoding examples in your lib

**Comment by manuelbl** [comment]
This library is able to decode the text that has been retrieved from the QR code:

```
Bill billData = QRBill.decodeQrCodeText(qrText);
```

In addition, separate software is required to scan the QR code (from an image) and retrieve the text. iOS and Android provide such features out of the box as part of the operating system. For other platforms, third party libraries exist. But I'm not familiar with any of those.

**Comment by endovitskayaV** [comment]
Thanks
