### ISSUE TITLE
invoice number not set in StrdBkgInf

### ISSUE THREAD

**Issue by gesteur** [manuelbl/SwissQRBill#15]
Hi Manuel,

shouldn't this line check if invoice NR is not null?

https://github.com/manuelbl/SwissQRBill/blob/6b197a93e6f05f9fa6e06552aab5ce428249b37c/generator/src/main/java/net/codecrete/qrbill/generator/SwicoS1Encoder.java#L48

**Comment by manuelbl** [comment]
Yes, indeed. I'll prepare a fix.

**Comment by manuelbl** [comment]
Fixed in version 2.3.6.

**Comment by gesteur** [comment]
Many thanks :)
