### ISSUE TITLE
Leading zero amount less then 1

### ISSUE THREAD

**Issue by patrickpei-zz** [manuelbl/SwissQRBill#16]
Hi 

The Raiffeisen App indicates an error when i scan a qrcode with an amount less then 1.00.
Other Apps accept this amount.
The support of the Raiffeisen told me the qrcode is not correct.

Raiffeisen App shows following error:

*Das Element Amt in (QRCH/CcyAmt) auf Zeile 19 ist ungültig.
Felddefinition: Das Element Betrag ist ohne führende Nullen inklusive Dezimaltrennzeichen und 2 Nachkomastellen anzugeben. Dezimal, maximal 12 Stellen zulässig, inklusive Dezimaltrennzeichen. Als Dezimaltrennzeichen ist nur das Punktzeichen (.) zulässig.
Betrag
Betrag der Zahlung

01: SPC
02: 0200
03: 1
04: CH7506900054228610001
05: K
06: Treson AG
07: Linsebühlstrasse 66
08: 9000 St. Gallen
09: 
10: 
11: CH
12: 
13: 
14: 
15: 
16: 
17: 
18: 
19: 0.50
20: CHF
21: K
22: Paritätische Berufskommission für das Bauhauptgewerbe Kanton Schaffhau
23: Winkelriedstrasse 32
24: 8203 Schaffhausen
25: 
26: 
27: CH
28: NON
29: 
30: Rechnung Nr. TEST 1 / Kontrolle für Demo Firma AG
31: EPD
32:

**Comment by manuelbl** [comment]
Thanks for pointing this out. It seems to be a bug in this library. I'll investigate it further and will fix it soon if needed.

It's surprising that the Raiffeisen app is so picky. I don't see any value in it for their customers.

**Comment by gexclaude** [comment]
"leading zeroes" makes sense to me, that an amount of 42.21 should not be preceded by additional leading zeroes. 0.50 seems very reasonable to me and scanning app should be more tolerant than generators regarding details from the spec, where it does not matter. 

I would not considering this a bug in your library @manuelbl , we do the same and all validators (SIX, UBS, PostFinance, Swico Validators and our own) consider this being a valid example. Raiffeisen should fix.

**Comment by gexclaude** [comment]
I would argue that this is an ambiguous detail. It is obvious that 0042.21 is not allowed. I agree with your goal, we do chase the same. Just make sure you do not make things worse. Others scanning/processing may parse/validate using patterns like #.## and could fail with only .##

Raiffeisen did have other issues too, afaik

**Comment by manuelbl** [comment]
It's now fixed in version 2.4.1.

It works in the Raiffeisen app (The leading zero is even omitted in the UI!):

![Raiffeisen App](https://user-images.githubusercontent.com/10954524/87576435-aeb84d80-c6d1-11ea-878f-c0e23b9e1ec9.png)

It still validates with the SIX validator and still scans with UBS Mobile Banking app.

**Comment by gexclaude** [comment]
Of course it is up to you how you like to handle this in your library. However we should ask SIX about this and let them improve in further minor revisions of the implementation guidelines and/or add an FAQ entry. Why? Because all QR bill collaborators should strive to get a precise understanding of what is valid or not. And implement it accordingly. I just tested QR bill generation using different generator tools with amount ".50" and checked result. All of which I tested wrote "0.50" to the SPC. 

https://ubs-paymentstandards.ch/
https://www.postfinance.ch/de/privat/support/tools-rechner/qr-generator.html/qrbill/Index.do
https://qr-rechnung.net/
https://qr-rechnung.online/
http://demo.qr-invoice.ch/app/index.html#/
https://qrportal.ch/?lang=de

Except the last one, qrportal wrote the value as it was entered. If ".50" was entered, ".50" was written to SPC. "0.50" if leading 0 was entered.

I will contact SIX.

**Comment by gexclaude** [comment]
Okay, so I wrote a mail to SIX.

Just to let you know - UBS Testplatform does not accept ".50"
![image](https://user-images.githubusercontent.com/416252/87636340-e90d0380-c740-11ea-854f-a0b2d54ddb98.png)

Neither does an Mobile App Scanning SDK that I am aware of. 

I hope to get feedback from SIX soon.

**Comment by manuelbl** [comment]
Thanks a lot for your effort. This is very valuable for good interoperability. I appreciate it.

I hope you have a good contact at SIX. I once contacted them via the SIX Validation Portal regarding a clarification of the newline after EPD. The answer took quite long, was contradicting in itself and didn't answer my primary question. When I then answered to the more or less anonymous email, I never got an answer again.

It's very interesting to see that the specification for this detail is unambiguous (no leading zero), yet everybody seems to have it implemented incorrectly...

**Comment by gexclaude** [comment]
I asked

    Es ist folgende Frage bzgl. Abbildung des Betrags im SPC aufgekommen.
    
    Auszug der Implementation Guidelines:
    «Das Element Betrag ist ohne führende Nullen inklusive
    Dezimaltrennzeichen und 2 Nachkomastellen anzugeben.
    Dezimal, maximal 12 Stellen zulässig, inklusive
    Dezimaltrennzeichen. Als Dezimaltrennzeichen ist nur das
    Punktzeichen (.) zulässig.»
     
    Soweit ist klar, dass ein Betrag wie CHF 42 als 42.00 abzubilden ist. Nicht aber als 0042 oder 042.0 usw.
    Was ist aus Sicht SIX im Fall von 50 Rappen gültig?
    .50
    0.50
    Beide Varianten?

Got the following answer:

    Es sind beide Varianten zulässig.
    
    Aus Gründen der Lesbarkeit sollte aber 0.50 verwendet werden, da der Betrag im Sichtteil ja auch angegeben werden muss.

**Comment by manuelbl** [comment]
Is this answer in any way helpful? I think it causes additional confusion.

- If 0.50 is valid as well, the implementation guidelines must be updated
and it must be communicated. But I can't see any hint that SIX is planning
to do so.
- The "Lesbarkeit" argument is nonsense as the display and encoding for the
QR text are two separate things.

So far, your analysis of actual implementations is what stands out.
Obviously, the industry has implicitly agreed on preferring "0.50" over
".50".

I will probably revert the change to the library.

**Comment by gexclaude** [comment]
Is it helpful? Obviously not. But as both are "valid", I would also stick to "0.50". Our parser does accept ".50" too.

**Comment by manuelbl** [comment]
You regard the answer as not helpful and still pick the part you like. I discard the entire answer as non-authoritative.

Anyhow, "0.50" is probably the way to go (de-facto industry standard).

**Comment by gexclaude** [comment]
The answer was not helpful as I would have prefered an a) or b) too. It is not about what I like. I just tried to help here. Thanks.

**Comment by manuelbl** [comment]
Thanks as well. I very much appreciate your help.

**Comment by manuelbl** [comment]
Version 2.4.2 reverts to the old behavior, i.e. amounts smaller than 1.00 have a leading zero, e.g. `0.50`.

I think the intention of the specification was `0.50` but the wording says to use `.50`.

Therefore the Raiffeisen app is probably correct in their interpretation of the spec. But the app is not interoperable with the majority of the implementations. So they will have to change it.
