### ISSUE TITLE
PDFCanvas: support byte[] in addition to File/Path, translation or rectangle, font family

### ISSUE THREAD

**Issue by rhoehener** [manuelbl/SwissQRBill#17]
Awesome library!

I couldn't figure out how to include the PDF output in a Jasper report, only SVG variant, with resulted in unselectable text (glyph rendered). So I really wanted to include the PDF output directly (so people can copy paste the IBAN, for example). Problem was that the invoice also needed to have a correctly branded page footer.

Here's the hack I used to add the QR-Rg. to the last page of my generated invoices, shifted up. Taking byte[] instead of Path/File parameter.
Maybe it will provide ideas for future API enhancements. 

```
public class QrPdfCanvas extends PDFCanvas {
  @SuppressWarnings("unused")
  private static final Logger LOGGER = Logger.getLogger(QrPdfCanvas.class.getName());

  public QrPdfCanvas(byte[] pdfBytes) throws Exception {
    super(210, 297);

    // font not supported, hardcoded in many places in super class
    //    setupFontMetrics("Arial");
    PDDocument document = PDDocument.load(pdfBytes);
    PDPage page = document.getPage(document.getNumberOfPages() - 1);
    PDPageContentStream contentStream = new PDPageContentStream(document, page, PDPageContentStream.AppendMode.APPEND, true, true);

    {
      Field field = PDFCanvas.class.getDeclaredField("document");
      field.setAccessible(true);
      field.set(this, document);
    }
    {
      Field field = PDFCanvas.class.getDeclaredField("contentStream");
      field.setAccessible(true);
      field.set(this, contentStream);
    }
  }

  @Override
  public void setTransformation(double translateX, double translateY, double rotate, double scaleX, double scaleY) throws IOException {
    translateX += 10;
    translateY += 50;
    super.setTransformation(translateX, translateY, rotate, scaleX, scaleY);
  }
}
```

**Comment by manuelbl** [comment]
How exactly is this class to be used? Is the PDF document generated by Jasper Report passed as *pdfBytes*?

If so, the main extension is that an existing PDF can be passed as a byte array (instead of as a file path). Would you agree?

BTW.: By shifting the QR bill upwards and adding a branded footer, you clearly violate the specification. The QR bill must be at the bottom. It should either be sent on paper with a perforation, or electronically such that it can be printed and easily cut off.

**Comment by rhoehener** [comment]
I use it like this:
```
        // pdfBytes generated in memory via dynamicreports.lbayer.com (wrapper around jasper reports)
        QrPdfCanvas canvas = new QrPdfCanvas(pdfBytes);
        QRBill.draw(bill, canvas);
        pdfBytes = canvas.toByteArray();
        canvas.close();
```

- position: didn't read the spec in detail, is that a hard requirement? could you maybe point me to the relevant section in the specification, please?
- i wanted 3 things: move it up, generate in-memory and change font to Arial. how doesn't matter, really, this is just the first way i found that worked.

**Comment by manuelbl** [comment]
Thanks for the additional context. I'll consider the additional requirements.

Most likely I won't implement changing the font from Helvetica to Arial. This change would require many additional PDF specific features regarding font embedding. Helvetica is one of the basic fonts that each PDF viewer must support while Arial is a Microsoft font that's usually only available on Windows systems (or Macs with Microsoft Office installed). So without font embedding, such a feature is problematic.

Regarding the positioning:

It's described in https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf (chapter 3.1, third bullet) and https://www.paymentstandards.ch/dam/downloads/style-guide-en.pdf (page 5, paragraph "Positioning of the payment part and receipt").

**Comment by rhoehener** [comment]
I didn't want to say I need any of this. I'm already happy with the result and moving on. Just wanted to say thank you and give you some feedback on the problems I encountered while using your library.

Thank you for the spec, reading now...

**Comment by manuelbl** [comment]
I like your use case and think you won't be the only one that comes across it. Therefore I appreciate that you have provided this feedback and will implement it even if you are not going to adapt your software later.

**Comment by rhoehener** [comment]
The spec is indeed quite clear about the position requirement. I was under the impression that one of the design goals of the QR bill was to allow for more flexibility in design and paper choice.

Until now, the invoices I generated only contained an IBAN and BIC. It's not intended to be paid by going to the post office or sending the paper to the bank.

Ideally I could only include the payment part without the receipt part, but there is no mention of that option, either.

I thought it would make sense to have the footer (including the page numbering "Page 3 of 3") also on the QR-Bill page. But I guess not 🤷‍♂️

**Comment by rhoehener** [comment]
Found that there is a "last page footer band" in jasper reports, which allows me to shift the last page footer up above the QR-bill, instead of shifting the QR-bill above the footer.

Very happy with this.

**Comment by manuelbl** [comment]
Release v2.4.3 adds a new constructor for PDFCanvas taking a byte array for the document.

I won't address the proposed font changes (sensible with font embedding only) and offset for QR bill (violates specification) for now.

**Comment by rhoehener** [comment]
Perfect, thank you very much! Already using it, seems to work great.
Font ist fine. And I'm not doing the shifting anymore.
