### ISSUE TITLE
getVersion() method for retrieving library version

### ISSUE THREAD

**Issue by benjaminkech** [manuelbl/SwissQRBill#18]
It would be nice to have a method to get the version of the library.

**Comment by manuelbl** [comment]
Version 2.4.2 introduces `QRBill.getLibraryVersion()`

**Comment by benjaminkech** [comment]
Unfortunately I get  a returning value of null (using gradle).

**Comment by manuelbl** [comment]
Are you using a pre-built package/jar of qrbill-generator (e.g. from Maven Central)? Or how have you integrated the library into your project?

**Comment by benjaminkech** [comment]
I'm using it with gradle from the repo Maven Central as a dependency.
`compile group: 'net.codecrete.qrbill', name: 'qrbill-generator', version: '2.4.2'`

**Comment by manuelbl** [comment]
The version number is taken from the jar's manifest. So it depends on the existence of the jar file (at run-time) and on the class loader being able to locate it.

Are you using a build mechanism that modifies or dissolves the jar file (Quarkus, Graal etc.)? Are you running in an environment that using special class loaders (application server etc.)?

**Comment by manuelbl** [comment]
Have you been able to get a reasonable version number? Or doesn't it work for your use case?
