### ISSUE TITLE
Dauerauftrag

### ISSUE THREAD

**Issue by warrioru** [manuelbl/SwissQRBill#21]
Is it possible to set the payment not as just one time, instead as a weekly / monthly recurring payment?

**Comment by manuelbl** [comment]
No, this is not part of the QR bill specification. 

There might be e-Banking systems that offer to convert a QR bill into a recurring payment. But since it's not part of the data structure, the user will have to enter the payment frequent, start and end date manually.

**Comment by warrioru** [comment]
ok, thanks for the information! Great work with the library btw!
