### ISSUE TITLE
Ignore Minor Version in Parsing

### ISSUE THREAD

**Issue by ChristianGegenschatz** [manuelbl/SwissQRBill#22]
There is a new SIX Passus for parsing and validating the Version

`Langfristig sollen die Teilnehmer nur die Hauptversion der IG, auf deren Grundlage der Swiss QR
Code erstellt wird, validieren (z.B. «02»). Die Unterversion dient lediglich zu Informationszwecken
und sollte nicht validiert werden (für die letzten zwei Zeichen sollten somit alle Eingaben – von «00»
bis «99» – erlaubt sein). Diese Lösung soll mit dem ersten «Breaking Change», spätestens aber bis
November 2022 von den Banken umgesetzt werden.`

Is there a plan to implement this?

**Comment by manuelbl** [comment]
I'm happy to change this soon but I haven't seen this new clause yet. Where did you find it?

**Comment by ChristianGegenschatz** [comment]
we get a document from SIX.
[QR-Rechnung – Validierung der Version des Swiss QR Codes.pdf](https://github.com/manuelbl/SwissQRBill/files/5260015/QR-Rechnung.Validierung.der.Version.des.Swiss.QR.Codes.pdf)

**Comment by manuelbl** [comment]
Umgesetzt in der Version 2.5.0.
