### ISSUE TITLE
Support of in memory file system (e.g. jimfs) for unit tests

### ISSUE THREAD

**Issue by marcelbaumann** [manuelbl/SwissQRBill#24]
Hello Manuel

Thank you for your great library. I used it in my application and as an example for students at the technical university of Luzern.
I am using an in-memory file system (jimfs) to implement unit and integration tests together with JUnit 5.

Would it be possible to alter the code of the constructor

public PDFCanvas(Path path, int pageNo) throws IOException {
        setupFontMetrics(PDF_FONT);
        document = **PDDocument.load(path.toFile());**
        preparePage(pageNo);
    }

into 

public PDFCanvas(Path path, int pageNo) throws IOException {
        setupFontMetrics(PDF_FONT);
        document = **PDDocument.load(Files.newInputStream(path);**
        preparePage(pageNo);
    }

(PDFDocument already provides a method with an input stream)

Path class supports other file systems (such as jimfs) but File class is a legacy class only supporting the default file system.

Thanks in advance for looking at it.

Sincerely

Marcel

**Comment by manuelbl** [comment]
Thanks for the input. I've changed it on the master branch. It will be included with the next release.

**Comment by marcelbaumann** [comment]
Thanks a lot for the fast response. Enjoy the day.
