### ISSUE TITLE
Javadoc is detected as false positive trojan

### ISSUE THREAD

**Issue by pogoflow** [manuelbl/SwissQRBill#28]
Windows defender thinks that the javadoc from the current release is a threat:
![image](https://user-images.githubusercontent.com/6523921/102486403-44814b80-4069-11eb-92ee-7466fac4174e.png)

**Comment by manuelbl** [comment]
Thanks for letting me know. I also think it's a false positive. There isn't anything I can do about it.

If you want to use the documentation as web pages (as opposed to integration with your IDE), you can view them at: https://www.codecrete.net/qrbill-javadoc/
