### ISSUE TITLE
Ultimate Creditor information

### ISSUE THREAD

**Issue by Knil23** [manuelbl/SwissQRBill#29]
Hello,

in QR implementation guide there is the possibility to define the creditor, implemented in the library, and the ultimate creditor that i can not find the implementation method.

Is it alreaby present? If not it will be implemented in future release?

Thank you in advance.
Knil

**Comment by manuelbl** [comment]
The implementation guidelines also say:

> The “Ultimate creditor” element is intended for use in the future but will not be used
> when QR-bill is introduced and should therefore not be filled in. 

At the moment, the ultimate creditor must not be filled in. Banks would likely reject such payments and/or the information would not be transmitted.

It will certainly be implemented in this library if and once the QR-bill standard is changed to include it.

**Comment by Knil23** [comment]
Hi,

thank you for your reply.
