### ISSUE TITLE
white area in the middle is 8x8 mm instead 7x7mm

### ISSUE THREAD

**Issue by elvisbegovic** [manuelbl/SwissQRBill#33]
Hi there,

I can be wrong but after several tests, it seems swiss cross with border  inside qrcode is 8mm instead 7mm

Indeed border with is 1mm instead 0.05  : 

![image](https://user-images.githubusercontent.com/2789203/120173514-62500080-c204-11eb-9ff6-b322602bcb42.png)

Pdf output from manuelbl/SwissQRBill : https://drive.google.com/file/d/12szTOiwzWzxnL2HMmh95AfInBm6Fkd0W/view?usp=sharing

ref: https://www.paymentstandards.ch/dam/downloads/style-guide-en.pdf page 13

![image](https://user-images.githubusercontent.com/2789203/120167243-cb804580-c1fd-11eb-867d-0fd150fc5d50.png)

What you think @manuelbl

**Comment by manuelbl** [comment]
The library creates a black area of 6x6mm and removes QR code dots to free
up an area of at least 7x7mm.
 So the question is: Does the specification of 7x7mm apply to the black
area of the Swiss flag or to the white area omitted in the QR code.

I've inspected the Adobe Illustrator file provided on
https://www.paymentstandards.ch/de/shared/communication-grid/swiss-qr-code.html
and found that the white area measures 7x7mm and the black area measures
6x6mm.

So I'm assuming that's the intention of the specification even though it's
not very explicit.

**Comment by elvisbegovic** [comment]
> @manuelbl : I've inspected the Adobe Illustrator file provided on
> https://www.paymentstandards.ch/de/shared/communication-grid/swiss-qr-code.html
> and found that the white area measures 7x7mm and the black area measures
> 6x6mm.

Yes, I agree with this, but in your lib white area is 8x8mm instead 7x7, isn't it ?  

![image](https://user-images.githubusercontent.com/2789203/120185526-9a5e4000-c212-11eb-8234-7dcd1c01e430.png)

**Comment by manuelbl** [comment]
This library creates the white area by removing entire QR code dots to free up at least 7x7mm. So depending on the dot size, the area becomes somewhat larger than 7x7mm.

It deviates from the standard ever so slightly. But is it a problem?

**Comment by elvisbegovic** [comment]
Askin me? no problem just report the bug. For me this qrcode can be 10x10cm or 272626x 272626cm  all scanner will recognize them. Btw other lib has correct 7x7mm.

Thus If I open issue it is a problem, seems some banks hired&pay a guy who does nothing but that all day.

actually lib does not follow qr standard and it is legit, independent of how lib add this swisscross it should be 7x7 « white area » and cross 6x6

actually cross is correctly 6x6 but white area is always 8x8 never more and never 7x7.
if you succeed to generate pdf with 7x7mm, you can share with me will try

You can try this one which is always 7x7mm http://demo.qr-invoice.ch/app/index.html#/
Under download>payment part&receipt

@manuelbl please close this if not relevant for you np

**Comment by manuelbl** [comment]
The more data is added to the invoice, the more likely it will be close to 7x7mm. In the below example, it's 7.33x7.33mm.

![QR Bill](https://user-images.githubusercontent.com/10954524/120245150-96f7a280-c26c-11eb-8035-0bfe05d09a52.png)
