### ISSUE TITLE
QR bill data is invalid: reference is invalid

### ISSUE THREAD

**Issue by cyrilfr** [manuelbl/SwissQRBill#37]
I'm using your great library to generate QR code only for my QR-bill in PNG and I get an exception when generating the QR code:

> net.codecrete.qrbill.generator.QRBillValidationError: QR bill data is invalid: reference is invalid (reference should be empty or start with "RF") (valid_iso11649_creditor_ref)

I generate the reference number using `Payments.createQRReference()` and it's formatted with `Payments.formatQRReferenceNumber()`. The generated string is a valid QR référence according to the standard.

> 00 00000 00000 00000 00000 00034

**Comment by manuelbl** [comment]
I'm afraid the error message is misleading.

In the context of the QR bill, "00 00000 00000 00000 00000 00034" is not a valid QR reference. Valid QR reference are based on one of the special IBANs in the 30000 – 31999 range, i.e. the QR reference must start with 30 or 31.

**Comment by cyrilfr** [comment]
It can be any ISR reference as well, including one with only 0 at the beginning.

**Comment by manuelbl** [comment]
Rereading my comment, I see that I have mixed up two things. But there is indeed a dependency between IBAN and reference that's likely not satisfied.

A QR reference (the numeric reference you are using) may only be used in combination with a QR-IBAN, i.e. an IBAN in the 30000 – 31999 range. What IBAN are you using? If you do not use a QR-IBAN, this library expects an ISO reference starting with "RF". (I will soon improve the error messages related to this dependency.)

**Comment by cyrilfr** [comment]
You're right, I didn't use a QR-IBAN for my tests so it totally makes sense.

**Comment by FredyWenger** [comment]
Hi
First also congrats for your good work (just checking it out in detail right now) 
Same issue here - glad I found this posting here...
If the error message would be changed to (If you don't use a special QR-IBAN, reference should be empty or start with "RF")
Then, it should be clear (i also have used our standard IBAN for the first tests).
Thank s for your good work!

**Comment by manuelbl** [comment]
Version 3 of the library is almost ready. It will considerably improve the error messages.

**Comment by FredyWenger** [comment]
O.K . thanks :-)

**Comment by LuFet** [comment]
Guten Tag
Vielen Dank für Ihre Arbeit.
Ich habe eine Frage: Wie kann ich die Sprache von dem Formular ändern? Bei mir ist Englisch.
Vielen Dank im Voraus!

**Comment by manuelbl** [comment]
Es geht so oder so ähnlich:

```
bill.getFormat().setLanguage(Language.DE);
```

**Comment by FredyWenger** [comment]
Oder (bin vor 30 Minuten über die gleiche Frage gestolpert ;-)
In **VB.NET** 
Dim EzAbschnitt As Bill = New Bill
 ' Sprache setzen:
EzAbschnitt.**Format.Language** = Language.DE
EzAbschnitt.Format.GraphicsFormat = GraphicsFormat.PNG ' Standard ist SVG

**Comment by FredyWenger** [comment]
Ich habe eine weitere Frage;
Offenbar werden zum EZ-Objekt automatisch **"Ränder" (links und rechts)** generiert. 
Wie können diese entfernt werden?
Was ich versucht habe:
Dim EzAbschnitt As Bill = New Bill
EzAbschnitt.Format.Language = Language.DE     ' Sprache setzen!
EzAbschnitt.Format.GraphicsFormat = GraphicsFormat.PNG ' Standard ist SVG 
' Margins auf 0 setzen ' funktioniert so nicht - kein Unterschied
 EzAbschnitt.Format.MarginLeft = 0
 EzAbschnitt.Format.MarginRight = 0
Sprache und Grafikformat funktionieren, bei den Margins sehe ich keinen Unterschied (Standard oder auf 0 setzen))

Besten Dank!

**Comment by manuelbl** [comment]
Dies ist ein offener Issue zu den irreführenden Fehlermeldungen der Java-Version von SwissQRBill. Darf ich bitte, für Fragen, die nichts mit diesem Issue zu tun haben und zudem die .NET-Version betreffen, einen separaten Issue unter https://github.com/manuelbl/SwissQRBill.NET/issues zu eröffnen.

**Comment by FredyWenger** [comment]
@manuelbl: Ich verstehe die Antwort nicht... die "irreführende Fehlermeldung" soll ja in der neuen Version angepasst werden und damit habe ich **kein problem**. 
Mein letztes Posting betrifft die **Ränder um die EZ-Grafik (vb.net) - wie können diese entfernt werden?**

**Comment by manuelbl** [comment]
@FredyWenger Mit "Dies ist ein offener Issue..." bezog ich mich auf die Webseite hier. Sie ist für Issue No 37 zum Thema der irreführenden Fehlermeldung. Für Fragen, Fehlermeldungen und Diskussionen zu anderen Themen sollte ein separater Issue und damit eine separate Webseite eröffnet und die Diskussion dort geführt werden. Also bitte nicht die Diskussionen vermischen. Das verhinderte eine gezielte Bearbeiten der Bugs und übrigen offenen Punkte.

Zudem gibt es zwei Versionen von SwissQRBill: eine Java- und eine .NET-Version. Also bitte den neuen Issue am richtigen Ort eröffnen: https://github.com/manuelbl/SwissQRBill.NET/issues für .NET-Version, https://github.com/manuelbl/SwissQRBill/issues für Java-Version.

**Comment by FredyWenger** [comment]
@manuelbl: Wie erwähnt, hätte ich nur gerne eine Antwort auf meine Frage (wie können die Ränder in der EZ-Grafik eliminiert werden).
Besten Dank.

**Comment by manuelbl** [comment]
@FredyWenger Ich werde die Frage nicht innerhalb dieses Issues beantworten, sonst geht es endlos hier weiter.

**Comment by FredyWenger** [comment]
**Jetzt** habe ich verstanden, was Sie meinen. Neues "Issue" eröffnet und sorry für meine "lange Leitung" (arbeite nicht oft mit Github. Dies ist hier meine letzte Meldung (wenn Sie wollen und können, dürfen Sie meine anderen Postings hier gerne auch löschen;-)

**Comment by manuelbl** [comment]
Release 3.0.0 has been released. The main change is that the validation messages have changed, in particular regarding the reference validation. The new messages are better at explaining the issue, in particular the valid and invalid combinations of reference type and IBAN type.
