### ISSUE TITLE
UTF-8 validation again with https://validation.iso-payments.ch

### ISSUE THREAD

**Issue by dummyphp** [manuelbl/SwissQRBill#38]
Dear Manuel,

First of all congratulations about your great job and sharing it.

I have downloaded one of your PDF example (https://www.codecrete.net/qrbill/bill) and tried the validation tool from the above mentionned website (see title). As an example :
(0002) - Fatal error: Invalid UTF-8 byte sequence at byte 11 in the file. This is what the byte sequence looks like in ISO-8859-1 encoding: "öäüß{10}1 0 o". The first byte of this sequence was skipped and replaced by '�' in the output
[Protocol.txt](https://github.com/manuelbl/SwissQRBill/files/7217043/Protocol.txt)
.

Should I ignore these errors ? 
Thank you for your help,
Kind Regards

**Comment by manuelbl** [comment]
Are you sure you have applied to correct test? The protocol says:

> Reference standard	: pain.002.001.03; ch; 02

This could mean that you have checked the file for PAIN.002 compliance, not for QR bill compliance.

Can you add one of the failing files to this issue?

**Comment by dummyphp** [comment]
oh, yes you're right, sorry. I will try to get access to the QR bill validator and keep you informed.
Not easy to understand all these compliance standards.

**Comment by dummyphp** [comment]
Just got access to the right validator :-)
Everything is working as expected without any error.
![2021-09-24_10h17_53](https://user-images.githubusercontent.com/23355604/134641968-abd7fdae-5c20-4997-bdb8-9201274fb6cd.png)
Kind Regards,
