### ISSUE TITLE
Validation 'Hinweis' @Postfinance 'Das Element 'AltPmt' darf nur geliefert werden, wenn es auch befüllt ist'

### ISSUE THREAD

**Issue by oizgtc** [manuelbl/SwissQRBill#39]
Bei der Validierung der QR Rechnung @ https://isotest.postfinance.ch/corporates/qrbill/validation 
wird neu ein Hinweis liefert ausgegeben :
Hinweis : Das Element 'AltPmt' darf nur geliefert werden, wenn es auch befüllt ist. 

Dies ist am 9.9.2021 noch nicht aufgetreten, Es scheint, dass sich die Validierung bei Postfinance geändert hat. 

Der Hinweis wird einerseits mit neu generierten QR Rechnungen (QR-Bill Version 2.5.3) angezeigt, wird aber auch mit den Online Beispielen https://github.com/manuelbl/SwissQRBill ausgegeben.

Postfinance Validierungs Output :
[Beispiel SwissQRBill.pdf.zip](https://github.com/manuelbl/SwissQRBill/files/7234686/Beispiel.SwissQRBill.pdf.zip)

**Comment by manuelbl** [comment]
Über diesen Punkt wurde schon reichlich diskutiert. Es geht – vereinfacht gesagt – darum, ob der Text im QR Code einen Zeilenumbruch am Ende hat oder nicht. Bei strenger Auslegung der Spezifikation sollte es keinen haben. Doch alle QR Codes in der offiziellen Spezifikation (Schweizer Implementation Guidelines QR-Rechnung) haben einen. Und einige Apps, die den QR Code für die Zahlungserfassung scannen, bestehen ebenfalls drauf.

PostFinance scheint sich nun der strengeren Auslegung angeschlossen zu haben. Voraussichtlich werde ich die Library in der nächsten Version entsprechend anpassen. In der Praxis sind aber mit der aktuellen Version keine Probleme zu erwarten.

**Comment by manuelbl** [comment]
Eine genauer Analyse hat gezeigt, dass die Spezifikation (Implementation Guide) in diesem Punkt angepasst worden ist (zwischen Version 2.1 und 2.2). Die ursprüngliche Spezifikation war widersprüchlich.

Die soeben veröffentliche Version 3.0.0 implementiert nun die neuste Spezifikation und lässt den Zeilenumbruch am Ende weg. So gibt es bei der Validierung im PostFinance-Portal keine Warnungen mehr.
