### ISSUE TITLE
Farbwahl Linien

### ISSUE THREAD

**Issue by Mafr25** [manuelbl/SwissQRBill#45]
Ist vermutlich momentan nicht relevant, solange nur in Schwarz gezeichnet wird:
Die Java-Methoden PDFCanvas::strokePath und PDFCanvas::fillPath enthalten die Zeilen
    int r = (color >> 16) & 0xff;
    int g = (color >> 8) & 0xff;
    int b = (color >> 8) & 0xff;
D.h. g=b. Gemeint vermutlich     
    int b = color & 0xff

**Comment by manuelbl** [comment]
Vielen Dank für den Hinweis. Ich werde es gerne im nächsten Release korrigieren.

**Comment by manuelbl** [comment]
Das Problem ist im neusten Release (3.0.0) behoben.
