### ISSUE TITLE
Error: Server Error The server encountered a temporary error and could not complete your request. Please try again in 30 seconds.

### ISSUE THREAD

**Issue by suneet133** [manuelbl/SwissQRBill#46]
Failed to list versions for net.codecrete.qrbill:qrbill-generator.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/net/codecrete/qrbill/qrbill-generator/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/net/codecrete/qrbill/qrbill-generator/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by manuelbl** [comment]
This is a temporary problem of JCenter / Bintray and not specifically related to this project.

To the best of my knowledge, JCenter is shutting down and has been frozen several month ago. You might need to migrate to another respository such as Maven Central anyway.

**Comment by suneet133** [comment]
Thanks, I migrated to Maven Central. It works now.
