### ISSUE TITLE
Issue is scanning QR code

### ISSUE THREAD

**Issue by tguruprasath** [manuelbl/SwissQRBill#51]
Hi,

I could generate the QR Bill. But when I scan, only the address 1 line is getting scanned instead of entire bill information. Below is my QR Bill.

![image](https://user-images.githubusercontent.com/100002289/154773595-b7f438ca-db24-4cd4-940e-016d614f91e2.png)

**Comment by manuelbl** [comment]
I assume you have used the camera app of your smart phone to scan the barcode. These apps do all sorts of smart things to help with everyday situations. But in this case, it's not helpful as data is lost.

Instead, try it with a barcode app without "smarts", e.g. the Scandit Scanner:

https://play.google.com/store/apps/details?id=com.scandit.demoapp&hl=en&gl=US

https://apps.apple.com/us/app/scandit-barcode-scanner/id453880584

**Comment by tguruprasath** [comment]
Thanks. I could able to scan with the app / tools mentioned.
