### ISSUE TITLE
How to download this whole project

### ISSUE THREAD

**Issue by Surya-0173** [manuelbl/SwissQRBill#52]

**Comment by manuelbl** [comment]
The ready-to-use files are hosted on Maven Central. Thus the easiest way to use it is to declare a dependency in the Maven or Gradle file or whatever Maven compatible build system you are using.

You can also download the entire project (in particular the source code) from the GitHub repository. The link to the zip file is provided by the green button labelled "Code" on the project home page.

Or you can download the jar files from the [Releases](https://github.com/manuelbl/SwissQRBill/releases) page.

**Comment by manuelbl** [comment]
Has this issue been resolved? If so, please close it. If not, please provide more information where you are stuck.
