### ISSUE TITLE
can we set already generated 27 digit Qrreference no directly 

### ISSUE THREAD

**Issue by Surya-0173** [manuelbl/SwissQRBill#59]
i have same logic in my code and genearte 27 digit ref no .can i set same no directly to Qrbill with same format

**Comment by manuelbl** [comment]
You can set the QR reference using [Bill.setReference()](https://www.codecrete.net/qrbill-javadoc/net/codecrete/qrbill/generator/Bill.html#setReference(java.lang.String)).

Doesn't the code example on the [home page](https://github.com/manuelbl/SwissQRBill#getting-started) work for you?

**Comment by Surya-0173** [comment]
thanks done.
