### ISSUE TITLE
Incompatbility with qrcode.jar 1.8 due to changed qrcode.encodeText method signature

### ISSUE THREAD

**Issue by Kusig** [manuelbl/SwissQRBill#60]
Updated to qrbill 3.0.2 which as well uses qrcode library 1.8 in maven dependency.  

Now I do get an exception in QRCode.draw(..) method that the method QrCode.encodeText could not be evaluated and called.

The method signatures within QRCode.encodeText() and others did change recently from String to CharSequence and this seems now to cause the problem because the method is called with the embeddedText string type instead. 

Side note: I'm using the library within Jasper with Java 1.8

**Comment by yelhouti** [comment]
Facing the same issue here, maybe you could use a fixed version here: https://github.com/manuelbl/SwissQRBill/blob/58866aae85ad9d3cb350dd190dd5fc99f06c57f4/generator/build.gradle#L137

**Comment by manuelbl** [comment]
Thanks for reporting this. And thanks for the workaround. I would have recommended the same workaround.

It was aware that a new version of the QR code library has been released this weekend. But I didn't expect any breaking changes as the major version number wasn't increased. I will investigate the best long-term remedy.

**Comment by manuelbl** [comment]
Contacted author of QR code library: https://github.com/nayuki/QR-Code-generator/issues/139

**Comment by saw303** [comment]
@manuelbl would it be better to declare a fixed version instead of relying to a semantic versioning range `[1.6.0,1.999999]`?

having ranged versioning makes builds hard to be reproducable. Or what is the intension by declaring ranges?

**Comment by Kusig** [comment]
Here's the maven equivalent working as expected (or as before):

`        <dependency>
            
            <groupId>net.codecrete.qrbill</groupId>
            <artifactId>qrbill-generator</artifactId>
            <version>3.0.2</version>
            <exclusions>
                
                
                <exclusion>
                    <groupId>io.nayuki</groupId>
                    <artifactId>qrcodegen</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.nayuki</groupId>
            <artifactId>qrcodegen</artifactId>
            <version>1.7.0</version>
        </dependency>
`

**Comment by saw303** [comment]
@manuelbl thank you for explaining. I understand the motivation and I don't want to start a debate about it. Don't get me wrong on this.

Isn't this issue demonstrating a huge downside of declaring version ranges? I mean due to an incompatible release of one of the transitive dependencies, the previously working release of the SwissQRBill doesn't work anymore or requires the workarounds for the consumers of SwissQRBill. From a library perspective this is an undesired situation.

But as mentioned. I don't wanna start a debate since I'm super happy that I found this open source project, that helps me a lot. Pointing out things is just a way of contributing.

**Comment by Kusig** [comment]
From my personal experience it is better to make dependencies sticky instead of version ranges. If one want, it could easily just overwrite the dependency with a new one by need anyhow as we do now but just the opposite way.  The advantage having a predictable and stable build over long time weights more I think.

**Comment by manuelbl** [comment]
A new version of the library has been released. It fixes the versions of the two main dependencies: PDFBox and QR-code-generator. It should appear on Maven Central within a few hours.

**Comment by saw303** [comment]
@manuelbl I can confirm that the new version 3.0.3 works correctly with `qrcodegen` 1.8.0. Thank you for the quick fix. I guess this issue can be closed for now.

**Comment by Kusig** [comment]
Confirmed as well. Works perfectly again. Thanks very much.
