### ISSUE TITLE
Can we add account no fields in additional information

### ISSUE THREAD

**Issue by Surya-0173** [manuelbl/SwissQRBill#65]
Can we add account no field in additional info or swiscobillInformation class

**Comment by manuelbl** [comment]
What account number would you like to add? A different one than the one that's always on a QR bill?

The *additional information* consists of the *unstructured message* (`setUnstructuredMessage()`) and the *billing information* (`setBillInformation()`). In the unstructured message, you can add any information you like. In the billing information, you are bound to the Swico standard and it does not include an account number field. But possibly the *customer reference* field works as well.

**Comment by Surya-0173** [comment]
I need to add customer account no

**Comment by manuelbl** [comment]
There is no standard for adding the customer's account number. If you have a requirement to so, it's likely part of a bilateral agreement between supplier and customer. So you have to discuss it with the customer where to put the account number.

**Comment by Surya-0173** [comment]
Ok thanks

**Comment by Surya-0173** [comment]
Ok thanks.
