### ISSUE TITLE
Ranged version dependency to qrcodegen caused runtime exception today

### ISSUE THREAD

**Issue by rhoehener** [manuelbl/SwissQRBill#67]
qrbill-generator:2.4.3 depends on qrcodegen:[1.6,)

Building today pulled qrcodegen:1.8.0, which caused this exception at runtime:

```
java.lang.NoSuchMethodError: io.nayuki.qrcodegen.QrCode.encodeText(Ljava/lang/String;Lio/nayuki/qrcodegen/QrCode$Ecc;)Lio/nayuki/qrcodegen/QrCode;
	at net.codecrete.qrbill.generator.QRCode.draw(QRCode.java:49)
```

Please consider using fixed dependency versions instead of ranges (also for pdfbox).

**Comment by manuelbl** [comment]
This exact issue has been fixed with release 3.0.3. It now uses fixed versions for dependencies.

Please upgrade to version 3.0.3.
