### ISSUE TITLE
Formatting address on invoice

### ISSUE THREAD

**Issue by Knil23** [manuelbl/SwissQRBill#68]
Hello,

is there a way to format the address on the invoice slip? I ask this because we have some address that are like the following:
_Mr. Pinco Pallino
c/o Pinco xxx
street xxxxx
9999 town_

Because of the lack of line and characters (70) the result on invoice is like the following and postfinance/banks doesn't like it
_Mr. Pinco Pallino
c/o Pinco xxx
9999 town_

is possible to make a character in the line that would make the printed address formatted but will be removed in the QRcode?
for example the text
_Mr. Pinco Pallino#@c/o Pinco xxx
street xxxxx
9999 town_

and the result on the invoice

_Mr. Pinco Pallino
c/o Pinco xxx
street xxxxx
9999 town_

Unfortunatly they way ours client write the address is not restricted (at least until 2024).

Thank you for your time and work.

saluti,

**Comment by manuelbl** [comment]
No, there is no way to format the addresses differently. 

Generally, I would recommend to separate the two middle lines with a comma:

_Mr. Pinco Pallino
c/o Pinco xxx, street xxxxx
9999 town_ 

If it concerns the debtor address, you can even omit one of the address lines as the address is mainly informational. The actual payment will contain the address of the owner of the account the money was paid from.
