### ISSUE TITLE
Extra trailing separator?

### ISSUE THREAD

**Issue by nguillaumin** [manuelbl/SwissQRBill#69]
Hi,

When generating a barcode with the example code in the README I'm getting an extra separator (CRLF) after the EPD. This is visible when scanning the barcode, or by adding `System.out.println("[" + QRBill.encodeQrCodeText(bill) + "]");` to the code snippet:

![image](https://user-images.githubusercontent.com/762512/171862696-dddfeb99-2575-4617-9fa4-7bc9b08020eb.png)

It looks in the spec that the last separator is supposed to be eliminated, see https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf page 25 section 4.1.4:

![image](https://user-images.githubusercontent.com/762512/171862868-a228fd0b-f47e-414e-9641-049dae917867.png)

One bank we're working with complained about this. Is it a bug, or am I missing something?

Thanks,

Nicolas

**Comment by manuelbl** [comment]
Are you using the latest version of the library?

This part of the specification has been ambiguous initially. When it was clarified, this library has been updated to reflect it.

**Comment by nguillaumin** [comment]
Thanks, I tried with the latest 3.0.3 and it's fixed indeed.
