### ISSUE TITLE
How to set qrbill payslip font to arial

### ISSUE THREAD

**Issue by Surya-0173** [manuelbl/SwissQRBill#70]
I change the pdf canvas file PDF_FONT="arial" and also format.setFontFamily("arial") but helvetica fault is displaying

**Comment by manuelbl** [comment]
The *PDFCanva*s class only supports Helvatica font. If you want to use another font, you would need to extend it. In particular, you'd need to implement font embedding. Font embedding is required for all fonts except the standard 14, which includes Helvetica.
