### ISSUE TITLE
Can we add some text on top of the page 

### ISSUE THREAD

**Issue by Surya-0173** [manuelbl/SwissQRBill#74]
Currently qrbill display on bottom of page that is fine. But i also need to add customer address top left corner of pdf page. How can i do this

**Comment by manuelbl** [comment]
This library has no means to add text outside the QR bill payment slip area. It assumes that you are already using a reporting / output software to generate the bill with all the invoicing details and then supports adding the QR bill payment slip.

There are several options:

- The reporting software might support SVG or PNG images. If so the QR bill payment slip can be added as an image within the report.
- If the reporting software generates a PDF document, the QR bill payment slip can be added in a separate step to the PDF document, either on an existing page or a new page. An example for this can be found in https://github.com/manuelbl/SwissQRBill/tree/master/examples/append_to_pdf
