### ISSUE TITLE
Can i increse of height of horizonal cutting dotted line 

### ISSUE THREAD

**Issue by Surya-0173** [manuelbl/SwissQRBill#76]
I need only horizontal cutting line to increse some mm.  Is this possible. How to increse if yes.

**Comment by manuelbl** [comment]
The location of the separator lines a given by the QR bill standard. This library will always draw them in the same location.

If you want them to be in a location outside the standard, you can turn them off, and then somehow draw them yourself. To turn them off:

```
bill.getFormat().setSeparatorType(SeparatorType.NONE);
```
