### ISSUE TITLE
Text orientation 

### ISSUE THREAD

**Issue by Surya-0173** [manuelbl/SwissQRBill#77]
It is possible to print text from right to left in put text method?

**Comment by manuelbl** [comment]
What do you mean with "put text method"? The [putText()](https://www.codecrete.net/qrbill-javadoc/net/codecrete/qrbill/canvas/Canvas.html#putText(java.lang.String,double,double,int,boolean)) method of the [Canvas](https://www.codecrete.net/qrbill-javadoc/net/codecrete/qrbill/canvas/Canvas.html) class?

If so, the answer is no. It was designed for QR bills, and QR bills only support a limited character set where right-to-left text is not relevant.

**Comment by manuelbl** [comment]
May I ask you to go through [your open issues](https://github.com/manuelbl/SwissQRBill/issues/created_by/Surya-0173) and close those that are done.
