### ISSUE TITLE
QR code Swiss cross missing in PDF

### ISSUE THREAD

**Issue by andlinger** [manuelbl/SwissQRBill#86]
When a QR code is generated in the following configuration, the Swiss cross is missing.

```java
bill.getFormat().setGraphicsFormat(GraphicsFormat.PDF);
bill.getFormat().setOutputSize(OutputSize.QR_CODE_WITH_QUIET_ZONE);
```

**Comment by manuelbl** [comment]
Thanks for reporting the bug. I will release a fix soon.

**Comment by manuelbl** [comment]
Release 3.1.1 fixes the issue. It will soon be available on Maven Central.

**Comment by andlinger** [comment]
Awesome! Thank you :)
