### ISSUE TITLE
Country code (wiki)

### ISSUE THREAD

**Issue by epsitec** [manuelbl/SwissQRBill#9]
You write in the wiki:

> And what about the country code? None of the examples shows a country. It's only part of the data embedded in the QR code. This library shows the country code at the start of the address line with postal code and town for all countries except Switzerland and Liechtenstein.

I had the same issue (https://github.com/swico/qr-bill/issues/1) and your choice makes perfect sense.

By the way, congratulations on your great work. I suggest that we link it from https://github.com/swico/qr-bill as a resource for developers looking for a well designed library.

**Comment by manuelbl** [comment]
I'm glad you like this library. You are of course welcome to link to it.

You have an interesting Wiki as well. Just spotted the invalid *Zahlteil* translation and will update it my libraries.
